package com.nefeed.dingtalkrobot.entity;

public class ActionLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.team_id
     *
     * @mbg.generated
     */
    private Integer teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.robot_id
     *
     * @mbg.generated
     */
    private Integer robotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.event
     *
     * @mbg.generated
     */
    private String event;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.log
     *
     * @mbg.generated
     */
    private String log;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.gmt_create
     *
     * @mbg.generated
     */
    private Integer gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.gmt_modify
     *
     * @mbg.generated
     */
    private Integer gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.del
     *
     * @mbg.generated
     */
    private Boolean del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.id
     *
     * @return the value of action_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.id
     *
     * @param id the value for action_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.user_id
     *
     * @return the value of action_log.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.user_id
     *
     * @param userId the value for action_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.team_id
     *
     * @return the value of action_log.team_id
     *
     * @mbg.generated
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.team_id
     *
     * @param teamId the value for action_log.team_id
     *
     * @mbg.generated
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.robot_id
     *
     * @return the value of action_log.robot_id
     *
     * @mbg.generated
     */
    public Integer getRobotId() {
        return robotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.robot_id
     *
     * @param robotId the value for action_log.robot_id
     *
     * @mbg.generated
     */
    public void setRobotId(Integer robotId) {
        this.robotId = robotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.event
     *
     * @return the value of action_log.event
     *
     * @mbg.generated
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.event
     *
     * @param event the value for action_log.event
     *
     * @mbg.generated
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.log
     *
     * @return the value of action_log.log
     *
     * @mbg.generated
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.log
     *
     * @param log the value for action_log.log
     *
     * @mbg.generated
     */
    public void setLog(String log) {
        this.log = log == null ? null : log.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.gmt_create
     *
     * @return the value of action_log.gmt_create
     *
     * @mbg.generated
     */
    public Integer getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.gmt_create
     *
     * @param gmtCreate the value for action_log.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Integer gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.gmt_modify
     *
     * @return the value of action_log.gmt_modify
     *
     * @mbg.generated
     */
    public Integer getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.gmt_modify
     *
     * @param gmtModify the value for action_log.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Integer gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.del
     *
     * @return the value of action_log.del
     *
     * @mbg.generated
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.del
     *
     * @param del the value for action_log.del
     *
     * @mbg.generated
     */
    public void setDel(Boolean del) {
        this.del = del;
    }
}