package com.nefeed.dingtalkrobot.entity;

public class RobotInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_info.robot_id
     *
     * @mbg.generated
     */
    private Integer robotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_info.team_id
     *
     * @mbg.generated
     */
    private Integer teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_info.robot_name
     *
     * @mbg.generated
     */
    private String robotName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_info.webhook
     *
     * @mbg.generated
     */
    private String webhook;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_info.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_info.robot_avatar
     *
     * @mbg.generated
     */
    private String robotAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_info.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_info.gmt_create
     *
     * @mbg.generated
     */
    private Integer gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_info.gmt_modify
     *
     * @mbg.generated
     */
    private Integer gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_info.del
     *
     * @mbg.generated
     */
    private Boolean del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_info.robot_id
     *
     * @return the value of robot_info.robot_id
     *
     * @mbg.generated
     */
    public Integer getRobotId() {
        return robotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_info.robot_id
     *
     * @param robotId the value for robot_info.robot_id
     *
     * @mbg.generated
     */
    public void setRobotId(Integer robotId) {
        this.robotId = robotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_info.team_id
     *
     * @return the value of robot_info.team_id
     *
     * @mbg.generated
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_info.team_id
     *
     * @param teamId the value for robot_info.team_id
     *
     * @mbg.generated
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_info.robot_name
     *
     * @return the value of robot_info.robot_name
     *
     * @mbg.generated
     */
    public String getRobotName() {
        return robotName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_info.robot_name
     *
     * @param robotName the value for robot_info.robot_name
     *
     * @mbg.generated
     */
    public void setRobotName(String robotName) {
        this.robotName = robotName == null ? null : robotName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_info.webhook
     *
     * @return the value of robot_info.webhook
     *
     * @mbg.generated
     */
    public String getWebhook() {
        return webhook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_info.webhook
     *
     * @param webhook the value for robot_info.webhook
     *
     * @mbg.generated
     */
    public void setWebhook(String webhook) {
        this.webhook = webhook == null ? null : webhook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_info.type
     *
     * @return the value of robot_info.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_info.type
     *
     * @param type the value for robot_info.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_info.robot_avatar
     *
     * @return the value of robot_info.robot_avatar
     *
     * @mbg.generated
     */
    public String getRobotAvatar() {
        return robotAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_info.robot_avatar
     *
     * @param robotAvatar the value for robot_info.robot_avatar
     *
     * @mbg.generated
     */
    public void setRobotAvatar(String robotAvatar) {
        this.robotAvatar = robotAvatar == null ? null : robotAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_info.status
     *
     * @return the value of robot_info.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_info.status
     *
     * @param status the value for robot_info.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_info.gmt_create
     *
     * @return the value of robot_info.gmt_create
     *
     * @mbg.generated
     */
    public Integer getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_info.gmt_create
     *
     * @param gmtCreate the value for robot_info.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Integer gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_info.gmt_modify
     *
     * @return the value of robot_info.gmt_modify
     *
     * @mbg.generated
     */
    public Integer getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_info.gmt_modify
     *
     * @param gmtModify the value for robot_info.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Integer gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_info.del
     *
     * @return the value of robot_info.del
     *
     * @mbg.generated
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_info.del
     *
     * @param del the value for robot_info.del
     *
     * @mbg.generated
     */
    public void setDel(Boolean del) {
        this.del = del;
    }
}