server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/dingtalk-robot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
mybatis:
  # 重要配置
  type-aliases-package: com.nefeed.dingtalkrobot.entity
  mapper-locations: classpath:mapping/*.xml