server:
  port: 8080
devtools:
  livereload:
    #是否支持livereload
    enabled: true
    port: 35729
  restart:
    #是否支持热部署
    enabled: true
logging:
  config: classpath:log4j2-dev.xml
spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dingtalk-robot?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 2
      min-idle: 1
      max-active: 8
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
mybatis:
  # 重要配置
  type-aliases-package: com.nefeed.dingtalkrobot.entity
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
