package com.nefeed.dingtalkrobot.dao;

import com.nefeed.dingtalkrobot.entity.ActionLog;

public interface ActionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbg.generated
     */
    int insert(ActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbg.generated
     */
    int insertSelective(ActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbg.generated
     */
    ActionLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActionLog record);
}