package com.nefeed.dingtalkrobot.dao;

import com.nefeed.dingtalkrobot.entity.CronInfo;

public interface CronInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cron_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cronId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cron_info
     *
     * @mbg.generated
     */
    int insert(CronInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cron_info
     *
     * @mbg.generated
     */
    int insertSelective(CronInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cron_info
     *
     * @mbg.generated
     */
    CronInfo selectByPrimaryKey(Integer cronId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cron_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CronInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cron_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CronInfo record);

    /**
     * 获取最新的生效定时执行器
     */
    CronInfo findActiveOne();
}