package com.nefeed.dingtalkrobot.dao;

import com.nefeed.dingtalkrobot.entity.UtRelation;

public interface UtRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ut_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ut_relation
     *
     * @mbg.generated
     */
    int insert(UtRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ut_relation
     *
     * @mbg.generated
     */
    int insertSelective(UtRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ut_relation
     *
     * @mbg.generated
     */
    UtRelation selectByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ut_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UtRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ut_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UtRelation record);
}